TASK_TYPE: few_shot_action
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 3.0
  DATASET: Ssv2_few_shot
  META_BATCH: true  # meta or not
  NUM_SAMPLES: 1000000
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 5
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 30000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 1000
  BATCH_SIZE: 4 # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 4
  CLASS_NAME: [
               'Approaching [something] with your camera',
               'Attaching [something] to [something]',
               'Bending [something] until it breaks',
               'Burying [something] in [something]',
               'Dropping [something] onto [something]',
               'Holding [something] behind [something]',
               'Holding [something] next to [something]',
               'Holding [something] over [something]',
               'Laying [something] on the table on its side, not upright',
               'Letting [something] roll along a flat surface',
               'Letting [something] roll down a slanted surface',
               'Lifting up one end of [something] without letting it drop down',
               'Lifting a surface with [something] on it until it starts sliding down',
               'Lifting up one end of [something], then letting it drop down',
               'Moving away from [something] with your camera',
               'Moving [part] of [something]',
               'Moving [something] across a surface until it falls down',
               'Moving [something] across a surface without it falling down',
               'Moving [something] and [something] away from each other',
               'Moving [something] and [something] so they collide with each other',
               'Piling [something] up',
               'Plugging [something] into [something]',
               'Poking a stack of [something] without the stack collapsing',
               'Poking [something] so it slightly moves',
               "Poking [something] so lightly that it doesn't or almost doesn't move",
               'Poking [something] so that it spins around',
               'Pouring [something] into [something]',
               'Pretending or failing to wipe [something] off of [something]',
               'Pretending or trying and failing to twist [something]',
               'Pretending to open [something] without actually opening it',
               'Pretending to poke [something]',
               'Pretending to put [something] on a surface',
               'Pretending to put [something] onto [something]',
               'Pretending to put [something] underneath [something]',
               'Pretending to spread air onto [something]',
               'Pretending to turn [something] upside down',
               'Pulling [something] from right to left',
               'Pulling [something] onto [something]',
               'Pulling two ends of [something] so that it separates into two pieces',
               "Pushing [something] so that it almost falls off but doesn't",
               'Pushing [something] so that it falls off the table',
               'Pushing [something] so that it slightly moves',
               'Putting [number of] [something] onto [something]',
               'Putting [something] behind [something]',
               'Putting [something] in front of [something]',
               'Putting [something] into [something]',
               "Putting [something] onto a slanted surface but it doesn't glide down",
               'Putting [something that cannot actually stand upright] upright on the table, so it falls on its side',
               'Removing [something], revealing [something] behind',
               'Showing [something] behind [something]',
               'Showing [something] to the camera',
               'Showing that [something] is empty',
               'Spilling [something] behind [something]',
               'Spilling [something] next to [something]',
               'Spreading [something] onto [something]',
               'Stacking [number of] [something]',
               'Taking [one of many similar things on the table]',
               'Throwing [something] in the air and catching it',
               "Tilting [something] with [something] on it slightly so it doesn't fall down",
               'Tipping [something] with [something in it] over, so [something in it] falls out',
               'Touching (without moving) [part] of [something]',
               'Turning the camera left while filming [something]',
               'Uncovering [something]',
               'Wiping [something] off of [something]'
               ]
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true


TEST:
  ENABLE: false
  DATASET: Ssv2_few_shot
  BATCH_SIZE: 4 # Same with NUM_GPUS
  CLASS_NAME: [
               'Dropping [something] into [something]',
               'Failing to put [something] into [something] because [something] does not fit',
               'Letting [something] roll up a slanted surface, so it rolls back down',
               'Moving [something] towards the camera',
               'Opening [something]',
               'Poking a hole into [some substance]',
               'Poking a hole into [something soft]',
               'Poking a stack of [something] so the stack collapses',
               'Pretending to take [something] from [somewhere]',
               'Pushing [something] off of [something]',
               'Pushing [something] with [something]',
               'Putting [something] next to [something]',
               'Putting [something] on a surface',
               'Putting [something] on the edge of [something] so it is not supported and falls down',
               'Putting [something] upright on the table',
               'Rolling [something] on a flat surface',
               'Scooping [something] up with [something]',
               '[Something] falling like a feather or paper',
               'Spinning [something] that quickly stops spinning',
               'Squeezing [something]',
               'Taking [something] out of [something]',
               'Twisting (wringing) [something] wet until water comes out',
               'Twisting [something]',
               'Unfolding [something]'
              ]
  TEST_SET: val
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

DATA:
  DATA_ROOT_DIR: /mnt/workspace/SSv2/
  ANNO_DIR: ./configs/projects/CLIPFSAR/ssv2_small/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224 # 84  # 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.00005
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 2000
  STEPS: [0, 4, 6]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.00002
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
# add bn, use same lr settings as server

VIDEO:
  HEAD:
    NAME: CNN_OTAM_CLIPFSAR
    BACKBONE_NAME: "RN50"
    #BACKBONE_NAME: "ViT-B/16"

  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 4
OUTPUT_DIR: output/CLIPFSAR_SSv2_Small_1shot


